# Spring Boot Application Configuration
server:
  port: 8080

spring:
  application:
    name: SpringBootStudy2023

# DataSource Configuration for MariaDB
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_boot_study
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

# JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql

# Logging Configuration
logging.level:
  org.hibernate.SQL: debug

# Jwt Configuration
jwt:
  secret: jhlee9462
  expire: 3600